version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: "Etc/UTC"
    groups:
      actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: "Etc/UTC"
    groups:
      go-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
