#!/usr/bin/env bash
# PreToolUse hook: blocks edits to the docs/ directory.
# docs/ is auto-generated by tfplugindocs — run `go generate` instead.

raw=$(cat)

tool_name=$(echo "$raw" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('tool_name',''))" 2>/dev/null) || exit 0
file_path=$(echo "$raw" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('tool_input',{}).get('file_path',''))" 2>/dev/null) || exit 0

case "$tool_name" in
  Write|Edit|NotebookEdit) ;;
  *) exit 0 ;;
esac

if echo "$file_path" | grep -qiE '(^|[/])docs[/]'; then
  python3 -c "
import json
print(json.dumps({
  'hookSpecificOutput': {
    'hookEventName': 'PreToolUse',
    'permissionDecision': 'deny',
    'permissionDecisionReason': 'Direct edits to docs/ are not allowed. The docs/ directory is auto-generated by tfplugindocs. Run \`go generate\` to regenerate it.'
  }
}))
"
  exit 2
fi

exit 0
