# PreToolUse hook: blocks edits to the docs/ directory.
# docs/ is auto-generated by tfplugindocs — run `go generate` instead.

$raw = $input | Out-String
try {
    $hook = $raw | ConvertFrom-Json
} catch {
    exit 0
}

$toolName = $hook.tool_name
$toolInput = $hook.tool_input

$editTools = @("Write", "Edit", "NotebookEdit")
if ($toolName -notin $editTools) {
    exit 0
}

$paths = @()
if ($toolInput.file_path) { $paths += $toolInput.file_path }

$docsPattern = [regex]::new('(^|[/\\])docs[/\\]', 'IgnoreCase')
foreach ($p in $paths) {
    if ($docsPattern.IsMatch($p)) {
        @{
            hookSpecificOutput = @{
                hookEventName            = "PreToolUse"
                permissionDecision       = "deny"
                permissionDecisionReason = "Direct edits to docs/ are not allowed. The docs/ directory is auto-generated by tfplugindocs. Run ``go generate`` to regenerate it."
            }
        } | ConvertTo-Json -Depth 5 | Write-Output
        exit 2
    }
}

exit 0
